// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto
// Protobuf C++ Version: 5.26.1

#include "data.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace habit_data {

inline constexpr habit_data::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : habit_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        device_timestamp_{0},
        data_{0},
        start_timestamp_{0},
        stop_timestamp_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR habit_data::habit_data(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct habit_dataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR habit_dataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~habit_dataDefaultTypeInternal() {}
  union {
    habit_data _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 habit_dataDefaultTypeInternal _habit_data_default_instance_;
}  // namespace habit_data
static ::_pb::Metadata file_level_metadata_data_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_data_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_data_2eproto = nullptr;
const ::uint32_t
    TableStruct_data_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::habit_data::habit_data, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::habit_data::habit_data, _impl_.device_timestamp_),
        PROTOBUF_FIELD_OFFSET(::habit_data::habit_data, _impl_.habit_id_),
        PROTOBUF_FIELD_OFFSET(::habit_data::habit_data, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::habit_data::habit_data, _impl_.start_timestamp_),
        PROTOBUF_FIELD_OFFSET(::habit_data::habit_data, _impl_.stop_timestamp_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::habit_data::habit_data)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::habit_data::_habit_data_default_instance_._instance,
};
const char descriptor_table_protodef_data_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\ndata.proto\022\nhabit_data\"w\n\nhabit_data\022\030"
    "\n\020device_timestamp\030\001 \001(\005\022\020\n\010habit_id\030\002 \001"
    "(\t\022\014\n\004data\030\003 \001(\005\022\027\n\017start_timestamp\030\004 \001("
    "\005\022\026\n\016stop_timestamp\030\005 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_data_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_data_2eproto = {
    false,
    false,
    153,
    descriptor_table_protodef_data_2eproto,
    "data.proto",
    &descriptor_table_data_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_data_2eproto::offsets,
    file_level_metadata_data_2eproto,
    file_level_enum_descriptors_data_2eproto,
    file_level_service_descriptors_data_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_data_2eproto_getter() {
  return &descriptor_table_data_2eproto;
}
namespace habit_data {
// ===================================================================

class habit_data::_Internal {
 public:
};

habit_data::habit_data(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:habit_data.habit_data)
}
inline PROTOBUF_NDEBUG_INLINE habit_data::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : habit_id_(arena, from.habit_id_),
        _cached_size_{0} {}

habit_data::habit_data(
    ::google::protobuf::Arena* arena,
    const habit_data& from)
    : ::google::protobuf::Message(arena) {
  habit_data* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, device_timestamp_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, device_timestamp_),
           offsetof(Impl_, stop_timestamp_) -
               offsetof(Impl_, device_timestamp_) +
               sizeof(Impl_::stop_timestamp_));

  // @@protoc_insertion_point(copy_constructor:habit_data.habit_data)
}
inline PROTOBUF_NDEBUG_INLINE habit_data::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : habit_id_(arena),
        _cached_size_{0} {}

inline void habit_data::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, device_timestamp_),
           0,
           offsetof(Impl_, stop_timestamp_) -
               offsetof(Impl_, device_timestamp_) +
               sizeof(Impl_::stop_timestamp_));
}
habit_data::~habit_data() {
  // @@protoc_insertion_point(destructor:habit_data.habit_data)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void habit_data::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.habit_id_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
habit_data::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(habit_data, _impl_._cached_size_),
              false,
          },
          &habit_data::MergeImpl,
          &habit_data::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void habit_data::Clear() {
// @@protoc_insertion_point(message_clear_start:habit_data.habit_data)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.habit_id_.ClearToEmpty();
  ::memset(&_impl_.device_timestamp_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.stop_timestamp_) -
      reinterpret_cast<char*>(&_impl_.device_timestamp_)) + sizeof(_impl_.stop_timestamp_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* habit_data::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 38, 2> habit_data::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_habit_data_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::habit_data::habit_data>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 device_timestamp = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(habit_data, _impl_.device_timestamp_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(habit_data, _impl_.device_timestamp_)}},
    // string habit_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(habit_data, _impl_.habit_id_)}},
    // int32 data = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(habit_data, _impl_.data_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(habit_data, _impl_.data_)}},
    // int32 start_timestamp = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(habit_data, _impl_.start_timestamp_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(habit_data, _impl_.start_timestamp_)}},
    // int32 stop_timestamp = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(habit_data, _impl_.stop_timestamp_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(habit_data, _impl_.stop_timestamp_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 device_timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(habit_data, _impl_.device_timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string habit_id = 2;
    {PROTOBUF_FIELD_OFFSET(habit_data, _impl_.habit_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 data = 3;
    {PROTOBUF_FIELD_OFFSET(habit_data, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 start_timestamp = 4;
    {PROTOBUF_FIELD_OFFSET(habit_data, _impl_.start_timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 stop_timestamp = 5;
    {PROTOBUF_FIELD_OFFSET(habit_data, _impl_.stop_timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\25\0\10\0\0\0\0\0"
    "habit_data.habit_data"
    "habit_id"
  }},
};

::uint8_t* habit_data::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:habit_data.habit_data)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 device_timestamp = 1;
  if (this->_internal_device_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_device_timestamp(), target);
  }

  // string habit_id = 2;
  if (!this->_internal_habit_id().empty()) {
    const std::string& _s = this->_internal_habit_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "habit_data.habit_data.habit_id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // int32 data = 3;
  if (this->_internal_data() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_data(), target);
  }

  // int32 start_timestamp = 4;
  if (this->_internal_start_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_start_timestamp(), target);
  }

  // int32 stop_timestamp = 5;
  if (this->_internal_stop_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_stop_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:habit_data.habit_data)
  return target;
}

::size_t habit_data::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:habit_data.habit_data)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string habit_id = 2;
  if (!this->_internal_habit_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_habit_id());
  }

  // int32 device_timestamp = 1;
  if (this->_internal_device_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_device_timestamp());
  }

  // int32 data = 3;
  if (this->_internal_data() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_data());
  }

  // int32 start_timestamp = 4;
  if (this->_internal_start_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_start_timestamp());
  }

  // int32 stop_timestamp = 5;
  if (this->_internal_stop_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_stop_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void habit_data::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<habit_data*>(&to_msg);
  auto& from = static_cast<const habit_data&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:habit_data.habit_data)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_habit_id().empty()) {
    _this->_internal_set_habit_id(from._internal_habit_id());
  }
  if (from._internal_device_timestamp() != 0) {
    _this->_impl_.device_timestamp_ = from._impl_.device_timestamp_;
  }
  if (from._internal_data() != 0) {
    _this->_impl_.data_ = from._impl_.data_;
  }
  if (from._internal_start_timestamp() != 0) {
    _this->_impl_.start_timestamp_ = from._impl_.start_timestamp_;
  }
  if (from._internal_stop_timestamp() != 0) {
    _this->_impl_.stop_timestamp_ = from._impl_.stop_timestamp_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void habit_data::CopyFrom(const habit_data& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:habit_data.habit_data)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool habit_data::IsInitialized() const {
  return true;
}

void habit_data::InternalSwap(habit_data* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.habit_id_, &other->_impl_.habit_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(habit_data, _impl_.stop_timestamp_)
      + sizeof(habit_data::_impl_.stop_timestamp_)
      - PROTOBUF_FIELD_OFFSET(habit_data, _impl_.device_timestamp_)>(
          reinterpret_cast<char*>(&_impl_.device_timestamp_),
          reinterpret_cast<char*>(&other->_impl_.device_timestamp_));
}

::google::protobuf::Metadata habit_data::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_data_2eproto_getter,
                                   &descriptor_table_data_2eproto_once,
                                   file_level_metadata_data_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace habit_data
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_data_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
